### PR TITLE
fix: get website to build again

### PR DESCRIPTION
**Pull request by lwjohnst86**
All the added files really messed with the website building. There were a lot of issues I had to debug and fix. One was removing the dependency on mlr3superlearner and lcmmtp, which have a sort of weird interdependency going on. I also had to stop all the tikz images from building with eval as false, because there were issues building them with tinytex. Plus, this is a HTML, best to use HTML native tools (and latex is a major pain to install and takes for ever).

In general, it's best to minimize the use of GitHub only packages, like all the ones in the remotes section. CRAN runs regular checks on packages to make sure they install and that dependencies are ok, but of course GitHub doesn't do that. Which was the problem with lcmmtp.

There were also a lot of latex equations in there that I tried to replace with `$$` as much as possible, but there are lots of formatting issues that I won't nor don't know how to fix.

### CODE REVIEW

**Comment by omarsilverman** [comment]
Thanks for having a look at it @lwjohnst86

**Comment by danielibsen** [comment]
Thank you so much Luke! I really didn't know what to do here. My backup solution would have been to remove many of their packages and simple show the code without running it. Merging different repositories is complicated. I will go through and fix all the figures according to you other pull request.

**Comment by lwjohnst86** [comment]
And it builds too: https://analysis-of-mechanisms.netlify.app/ woohoo 🎉

**Comment by danielibsen** [comment]
Yes it does now! I have some things to fix but it is great to have the link work again!

**Pull request merged**
